require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Caballeros' do
  config = use_native_modules!

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'CaballerosTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Caballeros-tvOS' do
  # Pods for Caballeros-tvOS

  target 'Caballeros-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
# Add the pod for Firebase Cloud Messaging
pod 'Firebase/Core'
pod 'Firebase/Messaging'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
